# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MURAKI_COMIC2
    ports:
      - "3307:3306"
    volumes:
      - ./MURAKI_COMIC2.sql:/docker-entrypoint-initdb.d/MURAKI_COMIC2.sql
    restart: always

  frontend:
    build:
      context: ./app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    restart: always

